name: Checks on Pull request
on:
  pull_request:
    branches:
     - main
jobs:
  build-test-lint:
   runs-on: ubuntu-latest
   container: node 20
   steps:   
      - uses: actions/checkout@v2
      - name: Build
        run: pnpm install && pnpm run build
      - name: Test
        run: pnpm install && pnpm run test
      - name: Lint
        run: pnpm install && pnpm run lint