name: Checks on Pull request
on:
  pull_request:
    branches:
     - main
jobs:
  build-test-lint:
   runs-on: ubuntu-latest
   steps:
      - name: Login to docker hub # Login to docker hub so we can push the image
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}    
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose run --rm app sh -c "pnpm install && pnpm run build"
      - name: Test
        run: docker-compose run --rm app sh -c "pnpm install && pnpm run test"